#### Laboratory work 4
### Tokiya Hiruma КН-221іб.е
<legend>Basics of the NumPy library</legend>

In [1]:
print(f'Variant: {ord("T") % 15 + 1}')

Variant: 10


1. Perform a set of exercises. All tasks should be performed in two ways:
<ol>
    <li>using universal functions of the NumPy library;</li>
    <li>using iterative constructions (using loops, list comprehensions, etc.</li>
</ol> 
For both cases, calculate the execution time of the script and compare the values.

2. Solve the system of linear equations using Cramer's formulas and check the result using:
<ol> 
    <li> matrix multiplication;</li>
    <li> inverse matrix;</li>
    <li> numpy.linalg.solve().</li>
</ol> 
Compare the results using numpy.allclose().

3. Calculate the value of the matrix expression
<ol>
    <li>using the universal functions of the NumPy library.</li>
    <li>using iterative constructions (using loops, list comprehensions, etc.).</li>
    <li>for both cases, calculate the execution time of the script and compare the values.</li>
</ol> 
4. Compare the results using numpy.allclose().
5. Push the created notebook on GitHub.
6. Prepare a report.

### Assignment 1
#### 1, 2, 3, 4, 6, 8, 11, 20, 21


In [2]:
import numpy as np 
import time
from math import sqrt

#### Exercise 1
Enter the number n. Output an array of size nхn, in which the diagonals
are numbers from 1 to n, and other elements are 0

In [4]:
#using universal functions of the NumPy library
def task_1_np():
    n = int(input('Enter n: '))
    start = time.time()
    matrix = np.zeros((n, n), dtype=int)
    np.fill_diagonal(matrix, np.arange(1, n+1))
    print(matrix)
    print(f'Time: {time.time() - start:.5f}s')
    
task_1_np()

Enter n: 20
[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0

In [35]:
#using iterative constructions (using loops, list comprehensions, etc.)
def task_1_iter():
    n = int(input('Enter n: '))
    start = time.time()
    matrix = []
    diagonal_value = 1
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(diagonal_value)
                diagonal_value += 1
            else: 
                row.append(0)
        matrix.append(row)
        row.clear
    print(matrix)
    print(f'Time: {time.time() - start:.5f}s')

task_1_iter()

Enter n: 20
[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0

#### Exercise 2
Enter the number n. Arrange 1 and 0 in a checkerboard pattern, starting
with 0 in a matrix of size nхn, using slicing.

In [16]:
#using universal functions of the NumPy library
def task_2():
    n = int(input('Enter n: '))
    start = time.time()
    arr = np.zeros((n, n), dtype=int)
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    print(arr)
    print(f'Time: {time.time() - start:.5f}s')
    
task_2()

Enter n: 5
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
Time: 0.00037s


#### Exercise 3
Enter 4 numbers n, m, r, c. Output an array of size nхm, in which in each r -th row and in each c-th column are 0, and other elements are equal to 1.

In [45]:
#using universal functions of the NumPy library
def task_3():
    n = int(input('Enter n: '))
    m = int(input('Enter m: '))
    r = int(input('Enter r: '))
    c = int(input('Enter c: '))
    start = time.time()
    arr = np.full((n, m), 1)
    arr[::r] = np.zeros(m, dtype='int')
    arr[:,c] = np.zeros(n, dtype='int')
    print(arr)
    print(f'Time: {time.time() - start:.5f}s')
    
task_3()

Enter n: 6
Enter m: 7
Enter r: 2
Enter c: 3
[[0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]]
Time: 0.00042s


#### Exercise 4
Enter the numbers n and m. Output an array of size nхm, in which the first line (line with zero index) are numbers from 0 to m-1, and all other elements of the matrix are equal to 0.

In [49]:
#using universal functions of the NumPy library
def task_4():
    n = int(input('Enter n: '))
    m = int(input('Enter m: '))
    start = time.time()
    arr = np.zeros((n, m), dtype='int')
    arr[:1] = np.arange(m)
    print(arr)
    print(f'Time: {time.time() - start:.5f}s')
    
task_4()

Enter n: 5
Enter m: 5
[[0 1 2 3 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Time: 0.00046s


#### Exercise 6
An array is entered from the keyboard. Replace all non-zero elements with -1.

In [7]:
#using universal functions of the NumPy library
def task_6():
    n = int(input())
    l = list(map(int, input("Array: ").strip().split()))
    start = time.time()
    arr = np.asarray(l)
    arr[arr != 0] = -1
    print(arr)
    print(f'Time: {time.time() - start:.5f}s')
task_6()

6
Array: -1 0 4 0 99 -12
[-1  0 -1  0 -1 -1]
Time: 0.00039s


#### Exercise 8
An array is entered from the keyboard. Count the number of zero and
non-zero elements in it.

In [8]:
#using universal functions of the NumPy library
def task_8():
    n = int(input())
    l = list(map(int, input("Array: ").strip().split()))
    start = time.time()
    arr = np.asarray(l)
    nonzero = np.count_nonzero(arr)
    zero = arr.size - nonzero
    print(f'Zeros count: {zero}, nonzeros count: {nonzero}')
    print(f'Time: {time.time() - start:.5f}s')
task_8()

10
Array: 1 2 3 0 4 1 0 2 -1 0
Zeros count: 3, nonzeros count: 7
Time: 0.00016s


###　いらない　⇩⇩⇩⇩

In [32]:
#using universal functions of the NumPy library
def assignment_1_numpy(array):
    start = time.time()
    a_min = np.amin(array)
    a_max = np.amax(array)
    a_mean = np.mean(array)
    a_dev = np.std(array)
    return f'Minimum: {a_min} \nMaximum: {a_max} \nMean: {a_mean:.3f} \nDeviation: {a_dev:.3f} \nTime: {time.time() - start:.3f}s'

In [4]:
#using iterative constructions (using loops, list comprehensions, etc.
def min_c(array):
    minimum = array[0]
    for elem in array:
        if elem < minimum:
            minimum = elem
    return minimum

def max_c(array):
    maximum = array[0]
    for elem in array:
        if elem > maximum:
            minimum = elem
    return maximum

def mean_c(array):
    mean = sum(array) / len(array)
    return mean

def deviation_c(array):
    mean = mean_c(array)
    deviations= [(x - mean) ** 2 for x in array]
    variance = sum(deviations) / len(array)
    return sqrt(variance)

def assignment_1_iteration(array):
    start = time.time()
    a_min = min_c(array)
    a_max = max_c(array)
    a_mean = mean_c(array)
    a_dev = deviation_c(array)
    return f'Minimum: {a_min} \nMaximum: {a_max} \nMean: {a_mean:.3f} \nDeviation: {a_dev:.3f} \nTime: {time.time() - start:.3f}s'

In [5]:
n = int(input('Enter n '))
m = int(input('Enter m '))

array = np.random.randint(100, size=(n*m))
print(f'\tUsing NumPy \n{assignment_1_numpy(array)}')
print(f'\tUsing Iterative constructions \n{assignment_1_iteration(array)}')

Enter n 500
Enter m 600
	Using NumPy 
Minimum: 0 
Maximum: 99 
Mean: 49.559 
Deviation: 28.859 
Time: 0.002s
	Using Iterative constructions 
Minimum: 0 
Maximum: 20 
Mean: 49.559 
Deviation: 28.859 
Time: 0.129s


<legend>Calculating using NumPy library is much more convenient and faster.</legend>

### Assignment 2

$$
\left\{
    \begin{array}\\
        4x_1 + x_2 -x_4 = -9 \\
        x_1 - 3x_2 + 4x_3 = 7 \\
        3x_2 - 2x_3 + 4x_4 = 12 \\
        x_1 + 2x_3 +4x_4 = 12 \\
    \end{array}
\right.
$$


#### 1. Create five 4x4 matrixes with the equations
$$
\Delta= \begin{vmatrix}
4 & 1 & 0 & -1 \\
1 & -3 & 4 & 0 \\
0 & 3 & -2 & 4 \\
1 & 2 & 0 & 4
\end{vmatrix}
$$

$$
\Delta_1 = \begin{vmatrix}
-9 & 1 & 0 & -1 \\
7 & -3 & 4 & 0 \\
12 & 3 & -2 & 4 \\
12 & 2 & 0 & 4
\end{vmatrix}
$$

$$
\Delta_2 = \begin{vmatrix}
4 & -9 & 0 & -1 \\
1 & 7 & 4 & 0 \\
0 & 12 & -2 & 4 \\
1 & 12 & 0 & 4
\end{vmatrix}
$$

$$
\Delta_3 = \begin{vmatrix}
4 & 1 & -9 & -1 \\
1 & -3 & 7 & 0 \\
0 & 3 & 12 & 4 \\
1 & 2 & 12 & 4
\end{vmatrix}
$$

$$
\Delta_3 = \begin{vmatrix}
4 & 1 & 0 & -9 \\
1 & -3 & 4 & 7 \\
0 & 3 & -2 & 12 \\
1 & 2 & 0 & 12
\end{vmatrix}
$$

In [11]:
A0 = np.array([[4, 1, 0, -1], [1, -3, 4, 0], [0, 3, -2, 4], [1, 2, 0, 4]])
A1 = np.array([[-9, 1, 0, -1], [7, -3, 4, 0], [12, 3, -2, 4], [12, 2, 0, 4]])
A2 = np.array([[4, -9, 0, -1], [1, 7, 4, 0], [0, 12, -2, 4], [1, 12, 0, 4]])
A3 = np.array([[4, 1, -9, -1], [1, -3, 7, 0], [0, 3, 12, 4], [1, 2, 12, 4]])
A4 = np.array([[4, 1, 0, -9], [1, -3, 4, 7], [0, 3, -2, 12], [1, 2, 0, 12]])

#### 2. Determine the determinate of each matrix

In [13]:
Ax = np.linalg.det(A0)
Ax1 = np.linalg.det(A1)
Ax2 = np.linalg.det(A2)
Ax3 = np.linalg.det(A3)
Ax4 = np.linalg.det(A4)

#### 3. Determine the values x1, x2, x3 and x4
$$
x_1=\frac{\Delta x_1}{\Delta x_0};
x_2=\frac{\Delta x_2}{\Delta x_0};
x_3=\frac{\Delta x_3}{\Delta x_0};
x_4=\frac{\Delta x_4}{\Delta x_0};
$$

In [15]:
x1 = Ax1 / Ax
x2 = Ax2 / Ax
x3 = Ax3 / Ax
x4 = Ax4 / Ax

print(f'x1: {x1:.2f}, x2: {x2:.2f}, x3: {x3:.2f}, x4: {x4:.2f}')

x1: 1.64, x2: -8.64, x3: -5.14, x4: 6.91
